# fly.toml app configuration file generated for caribevibes-system on 2025-07-07T01:10:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'caribevibes-system'
primary_region = 'bog'

[build]

[env]
  SPRING_PROFILES_ACTIVE = 'fly'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[vm]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1