# Configuración específica para Fly.io
# Solo logging a consola, sin archivos de log
spring:
  application:
    name: caribe-vibes-fly
    
  # Base de datos MySQL
  datasource:
    url: ${DATABASE_URL_CARIBE_VIBES:jdbc:mysql://database:3306/caribe_vibes}
    username: ${DATABASE_USERNAME_CARIBE_VIBES:user}
    password: ${DATABASE_PASSWORD_CARIBE_VIBES:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # Pool de conexiones optimizado para Fly.io
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 2
      leak-detection-threshold: 60000

  # JPA configurado para MySQL
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC

  # Flyway habilitado para migraciones
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    baseline-version: 0
    
  # Cache ligero para Fly.io
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=300s

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  compression:
    enabled: true
    min-response-size: 1024
  servlet:
    session:
      timeout: 30m
      cookie:
        secure: true
        http-only: true

# Logging solo a consola para Fly.io
logging:
  level:
    '[org.project.caribevibes]': INFO
    '[org.springframework.security]': WARN
    '[org.springframework.web]': WARN
    '[org.hibernate]': WARN
    '[com.zaxxer.hikari]': WARN
    '[org.flywaydb]': INFO
    '[org.springframework.boot]': INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints para Fly.io health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      
# Configuración de seguridad
security:
  jwt:
    secret: ${JWT_SECRET:your-fly-io-jwt-secret-key}
    expiration: 3600000

# Configuración de archivos (en memoria para Fly.io)
file:
  storage:
    type: filesystem
    path: /tmp/uploads
